// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKXfwAdF1BBbj7npSH-7tRTfDRAhk0wPk',
    appId: '1:465161482930:web:ed56c66a4554c6429f0fab',
    messagingSenderId: '465161482930',
    projectId: 'igaranti',
    authDomain: 'igaranti.firebaseapp.com',
    storageBucket: 'igaranti.firebasestorage.app',
    measurementId: 'G-NSCMPLSDG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEHzIOUIRhIxR5JzFe60nv1eU7tdh01Fw',
    appId: '1:465161482930:android:a58a6c824f346f059f0fab',
    messagingSenderId: '465161482930',
    projectId: 'igaranti',
    storageBucket: 'igaranti.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWT8HdtiIn8G9t9aAu1mhAxEUobgIsExo',
    appId: '1:465161482930:ios:466e04a720ce1f189f0fab',
    messagingSenderId: '465161482930',
    projectId: 'igaranti',
    storageBucket: 'igaranti.firebasestorage.app',
    iosBundleId: 'com.harfur.igaranti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWT8HdtiIn8G9t9aAu1mhAxEUobgIsExo',
    appId: '1:465161482930:ios:466e04a720ce1f189f0fab',
    messagingSenderId: '465161482930',
    projectId: 'igaranti',
    storageBucket: 'igaranti.firebasestorage.app',
    iosBundleId: 'com.harfur.igaranti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKXfwAdF1BBbj7npSH-7tRTfDRAhk0wPk',
    appId: '1:465161482930:web:612f4a6437e107e69f0fab',
    messagingSenderId: '465161482930',
    projectId: 'igaranti',
    authDomain: 'igaranti.firebaseapp.com',
    storageBucket: 'igaranti.firebasestorage.app',
    measurementId: 'G-DJ3WKDQ1HK',
  );
}